
const {
  APPWRITE_PROJECT_ID,
  APPWRITE_API,
  APPWRITE_DB,
  APPWRITE_COLLECTION_EXPERT,
  APPWRITE_COLLECTION_MEMBER,
  APPWRITE_COLLECTION_APPOINTMENT,
  APPWRITE_NEXT_PUBLIC_STORAGE_BUCKET_ID: BUCKET_ID,
  APPWRITE_NEXT_PUBLIC_ENDPOINT: ENDPOINT,
} = process.env